### ISSUE TITLE
Fix Gem Trader

### ISSUE THREAD

**Issue by 12Metatron** [Topkinsme/Color-Battle-Roles#18]
As it is, gem trader is basically unusable because no one can bypass the gems protection or steal the gem

suggested fix:

Gems are weak protection.
attacking a gem once with a normal attack will make it a cracked gem. strong attack cracks two gems
cracked gems no longer provide protection but still roleblock
if someone dies while holding a cracked gem, the cracked gem gets sent back to gem trader
if someone with a gem is strong attacked, then the gem is destroyed and sent out of circulation
a gem trader will not know if they have a cracked gem but when they get rid of a gem via trading or money, they will always choose cracked gems first, if they have any.

Also should make a separate info section for gems and cracked gems, like devils desc in werewovles

**Comment by Topkinsme** [comment]
LoG has also suggested we remove the ability to sell gems, which I agree with, it removes the cash being a variable factor (since it's easier to get on certain games and harder on others) and also serves no purpose if the gem trader is not broken.
