### ISSUE TITLE
check tribute

### ISSUE THREAD

**Issue by 12Metatron** [Topkinsme/Color-Battle-Roles#2]
no way to check what you had your tribute price as, and it doesn't even say it what you did in the confirmation message. which makes sense, there's some reasons to not want people to know what you did. but the combination of these two things makes it really easy to forget

**Comment by Topkinsme** [comment]
Wrong Repo but yeah it will be fixed.

**Comment by Topkinsme** [comment]
This was fixed in the latest bot update.
