### ISSUE TITLE
Potion master protection description.

### ISSUE THREAD

**Issue by Topkinsme** [Topkinsme/Color-Battle-Roles#3]
Potion master's prot says "For a night, and also doesn't expire until attacked?" So which is it?

**Comment by 12Metatron** [comment]
its perm until attacked, but doesnt protect during day. i think that's what you meant by that phrasing.

**Comment by Topkinsme** [comment]
I had meant it lasts till they get attacked, permanent protection of sorts.

**Comment by Topkinsme** [comment]
#9 should fix this
