### ISSUE TITLE
cult leader change

### ISSUE THREAD

**Issue by 12Metatron** [Topkinsme/Color-Battle-Roles#36]
similar to how the curse isnt activated when someone is tributed, I think unblockable attacks should also kill the target and not trigger the curse

**Comment by Topkinsme** [comment]
If someone dies while cursed, they join the cult, I don't see why an unstoppable kill should not convert someone.
Plus I don't want Unblockable kills to be ultimate, I still want things like Life Transferrer and negotiator to work for example.
I'm not closing this, if there's a strong argument for it I might consider it.

**Comment by Topkinsme** [comment]
This was voted against
