### ISSUE TITLE
Prince is too weak

### ISSUE THREAD

**Issue by Topkinsme** [Topkinsme/Color-Battle-Roles#73]
As it currently stands, the Prince role is too weak. There's no reason for a person to pick prince over the queen or the princess.

Possible buffs-
1. Prince can change their respawn time, to make it anything from 2 to 6 phases. (LoG)
2. Prince can weakly disguise as another team at the start of the game. (Ethan)
3. When the prince becomes king reduce all dead teammates respawn time by 1 phase (or 2) (Jayanna)
4. If the prince is respawning when the king dies, it'll auto respawn and become king. (Luffy) (My Preferrence)

**Comment by TheEighthDeadlySin** [comment]
My opinion on each potential buff:
- Lord of Galaxy: This ability could be useful, but also seems a bit weaker than the original Prince (seeing how the original Prince always respawned in 2 phases).
- Ethan: This ability seems extremely weak to be honest. Seeing how we normally play a 3 colour faction game (potentially increasing it to 4 if we have enough players), the disguise will likely only affect up to 1/2 teams (the other team which you disguise as will clearly know that you are disguised).
- Jayanna: This ability is either too OP, or completely redundant if your team manages to get the auction item which sets all of your team's respawn times to 2 phases.
- Luffy: This idea seems alright, however will potentially make it clear to the other teams that you were the Prince (making you quite a large target). Seems to be the most balanced with the Queen and Princess abilities at the current moment.

**Comment by TheEighthDeadlySin** [comment]
Maybe, as a potential buff, the Prince could have an ability which lets them become the King [should only apply after a specific period of time has passed, like 3 days]? The old King would then become a normal Warrior (maybe Ex Warrior). If this feels too weak, maybe add something like after this happens, the Prince gets coronation donations (like 3000 coins or something idk).
This is just me trying to think of other ideas.

**Comment by TheEighthDeadlySin** [comment]
Another idea is that the Prince could maybe generate more money for every phase change (like x1.25 or something).

**Comment by Topkinsme** [comment]
> Maybe, as a potential buff, the Prince could have an ability which lets them become the King [should only apply after a specific period of time has passed, like 3 days]? The old King would then become a normal Warrior (maybe Ex Warrior). If this feels too weak, maybe add something like after this happens, the Prince gets coronation donations (like 3000 coins or something idk).
This is just me trying to think of other ideas.

ooh, that does sound interesting. We could turn the king into a strong warrior for example. I like this idea, just need to work out what it turns into. Maybe for balancing, just a regular warrior might be the best. 

The only issue I have with this is the bot itself
There's no command to change roles in the database, so the old king will always have access to tribute and stuff

We can combat this by making a new role like the old king, which is warrior but royalty
or just make warrior into royalty (/j)

**Comment by Topkinsme** [comment]
> Another idea is that the Prince could maybe generate more money for every phase change (like x1.25 or something).

Sounds interesting, Not my goto choice tho
